# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev
- master

pool:
  name: dev
  demands:
  - Agent.Name -equals centos

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '17.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'build'

- task: DownloadSecureFile@1
  condition: eq(variables['build.sourceBranch'], 'refs/heads/dev')
  name: env
  displayName: 'Download env file'
  inputs:
    secureFile: 'env.dev.env'
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.TempDirectory)
    contents: '*.env'
    targetFolder: $(Build.SourcesDirectory)
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-$(build.sourceBranch).zip'
    replaceExistingArchive: true
  displayName: 'Archive'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'