# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev
- master

pool:
  name: dev
  demands:
  - Agent.Name -equals centos

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '17.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'build'

- task: DownloadSecureFile@1
  condition: eq(variables['build.sourceBranch'], 'refs/heads/dev')
  name: env
  displayName: 'Download env file'
  inputs:
    secureFile: 'env.dev.env'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.TempDirectory)
    contents: '*.env'
    targetFolder: $(Build.SourcesDirectory)

- script: |
    echo $sourceVersion
    commitHash=${sourceVersion:0:7}
    echo $commitHash
    echo "##vso[task.setvariable variable=commitHash]$commitHash" ## Set variable for using in other tasks.
  env: { sourceVersion: $(Build.SourceVersion) }
  displayName: Git Hash 7-digit
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.BuildId)-$(build.sourceBranchName)-$(commitHash).zip'
    replaceExistingArchive: true
  displayName: 'Archive'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.Name)'
    ArtifactName: '$(build.sourceBranchName)'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'